version: "3.1"
services:
  # mongo:
  #   container_name: mongo
  #   image: mvertes/alpine-mongo:4.0.5-0
  #   restart: always
  #   volumes:
  #     - ./data:/www/app/data
  #   ports:
  #     - 27017:27017
  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbitmq"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   tty: true
  #   labels:
  #     NAME: "rabbitmq"
  restapi:
    build:
      context: .
    ports:
      - "4009:3001"
      - "4010:80"
    container_name: restapi
    # command: nodemon -L ./bin/www
    volumes:
      - .:/www/app
    restart: on-failure
    # tty: true